### ISSUE TITLE
Addition: ChatGPT to generate music

### ISSUE THREAD

**Issue by luphoria** [PeterWaIIace/ChatGPTpayloads#2]
`Write a <parameters> song in ABC notation. Include chords.`
It doesn't seem to have any care for time signature, so it often does weird things. ABC notation is basic enough to simply ignore the issues though.
It writes songs that are generally pleasing enough to the ear.

Example of output to `Write a classical music-style song in ABC notation. Include chords.`:
```
X:1
T:Classical Song
M:4/4
L:1/4
Q:1/4=80
K:C
V:1
"C" C E G | "Am" A C E | "F" F A C | "G" G B D |
"C" C E G | "Am" A C E | "F" G A C | "G" G B D |
"C" C E G | "Am" A C E | "F" F A C | "G" G B D |
"C" C E G | "Am" A C E | "F" G A C | "G" G B D |
"C" C E G | "Am" A C E | "F" F A C | "G" G B D |
"C" C E G | "Am" A C E | "F" G A C | "G" G B D |
"C" C E G | "Am" A C E | "F" F A C | "G" G B D |
"C" C E G | "Am" A C E | "F" G A C | "G" G B D |
```
(You can play the songs on https://lpnz.org/abc-editor/)

**Comment by PeterWaIIace** [comment]
This is nice. I think I need to organise prompts a bit in the readme.
