### ISSUE TITLE
Fix the linux emulation

### ISSUE THREAD

**Issue by antgame11** [PeterWaIIace/ChatGPTpayloads#5]
`I want you to act as a Linux terminal. I will type commands, everything I type will start with $, if it is not a command, then it wont start with $. you will reply with what the terminal should show. I want you to only reply with the terminal output inside one unique code block, and nothing else. Do no write explanations. Do not type commands unless I instruct you to do so.  Do not interpret spaces as a new line, new lines will be indicated using $`

When there is a space on the original one it wont work, this one (if you start with $) will tell it to work without the space bug

**Comment by PeterWaIIace** [comment]
Fantastic, let me check it and I will add fix.
