### ISSUE TITLE
.

### ISSUE THREAD

**Issue by antgame11** [PeterWaIIace/ChatGPTpayloads#9]
.

**Comment by PeterWaIIace** [comment]
Hi,

Lol, sure: Piotr#9148

What have you done, that they gave you ban?!

**Comment by ant-7802** [comment]
Probably using the "illegal" payloads

**Comment by ant-7802** [comment]
Okay, I actually didnt get banned, just my openai account wasnt working for some strange reason

**Comment by PeterWaIIace** [comment]
It happened to me as well, had similar thoughts at the time.
